NUM_OF_VALUES = 13
NUM_OF_SUITES = 4
NUM_OF_ROUNDS = 4
# CHECK/CALL, RAISE, FOLD
BOT_ACTION_PROBS = [0.7, 0.2, 0.1]
ROUNDS = ["PREFLOP", "FLOP", "TURN", "RIVER"]
ACTIONS = {0: "CHECK", 1: "RAISE", 2: "FOLD"}
PREFLOP = 0
FLOP = 1
TURN = 2
RIVER = 3
